### ISSUE TITLE
Broken on bbc.co.uk

### ISSUE THREAD

**Issue by Foggalong** [gavinCD/Minf2Plugin#1]
Plugin can't load 'overview' or 'site settings and info' when visiting [bbc.co.uk](https://www.bbc.co.uk/)

![Screenshot from 2023-04-08 14-19-33](https://user-images.githubusercontent.com/5920259/230723507-3f02d5c4-b477-4d4a-b201-51106a169ee7.png)

**Comment by gavinCD** [comment]
Small issue with backend code with bbc.co.uk not being resolved to data associated with bbc. TLD's are now being removed correctly by the plugin application and information associated with bbc.co.uk is now being displayed correctly.
![image](https://user-images.githubusercontent.com/61881348/230725221-26617341-f327-4559-a819-1bc460bcfef4.png)
Thank you for finding this!! :)
